### ISSUE TITLE
Does not build on Suse SLES 11

### ISSUE THREAD

**Issue by Bouncner** [WGierke/tuk1_numa_a#12]
`Martin.Boissier@side:~/tuk1_2017/tuk1_numa_a/build> CXX=/usr/local/bin/c++  cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/local/share/cmake-3.8/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeTmp

  Run Build Command:"/usr/bin/gmake" "cmTC_87333/fast"

  /usr/bin/gmake -f CMakeFiles/cmTC_87333.dir/build.make
  CMakeFiles/cmTC_87333.dir/build

  gmake[1]: Entering directory
  `/hana/shared/home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_87333.dir/testCCompiler.c.o

  /usr/bin/cc -o CMakeFiles/cmTC_87333.dir/testCCompiler.c.o -c
  /home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTC_87333

  /usr/local/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_87333.dir/link.txt --verbose=1

  /usr/bin/cc -Wl,--print-map,-ltr,-lrt -rdynamic
  CMakeFiles/cmTC_87333.dir/testCCompiler.c.o -o cmTC_87333

  /usr/bin/ld: cannot find -ltr

  collect2: error: ld returned 1 exit status

  gmake[1]: *** [cmTC_87333] Error 1

  gmake[1]: Leaving directory
  `/hana/shared/home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeTmp'

  gmake: *** [cmTC_87333/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

-- Configuring incomplete, errors occurred!
See also "/home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeOutput.log".
See also "/home/Martin.Boissier/tuk1_2017/tuk1_numa_a/build/CMakeFiles/CMakeError.log".
Martin.Boissier@side:~/tuk1_2017/tuk1_numa_a/build>`

Any ideas?

**Comment by rs22** [comment]
So you're trying to compile with a gcc 7.1 compiler located in /usr/local/bin ? ~~Which version of CMake are you using?~~ (ah, 3.8 never mind)

My guess is that because you only specified the CXX compiler but not the CC compiler, CMake falls back to the cc in /usr/bin which has problems compiling the test binary meant for gcc 7.

```
/usr/bin/cc -Wl,--print-map,-ltr,-lrt -rdynamic
CMakeFiles/cmTC_87333.dir/testCCompiler.c.o -o cmTC_87333

/usr/bin/ld: cannot find -ltr

collect2: error: ld returned 1 exit status
```

Can you try to clear the CMake cache and re-configure with `CC=/usr/local/bin/gcc` set?

**Comment by Bouncner** [comment]
Thanks ... it did the trick.

`Martin.Boissier@side:~/tuk1_2017/tuk1_numa_a/build> CXX=/usr/local/bin/c++ CC=/usr/local/bin/gcc  cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release ..`

**Comment by Bouncner** [comment]
itte sowas auch kurz in der Readme anmerken. Wenn wir das später auf de SGI ausführen und ein paar Wochen ins Programmierland gegangen sind, könnte es weitere Stolpersteine geben. Lieber gleich gut dokumentieren (sollte reichen die von euch genutzt GCC-Version als Minimum zu nennen).
